export const scores = {
  1: {
    A: {
      friar: 0,
      newyork: 0,
      corn: 0,
      pool: 0,
      sleeping: 0,
      lobster: 0,
      squishy: 0,
      sweater: 0,
      time: 0,
      retro: 0,
      beach: 0,
      reindeer: 0
    },
    B: {
      friar: 0,
      newyork: 0,
      corn: 0,
      pool: 0,
      sleeping: 0,
      lobster: 0,
      squishy: 0,
      sweater: 0,
      time: 0,
      retro: 0,
      beach: 0,
      reindeer: 0
    },
    C: {
      friar: 0,
      newyork: 0,
      corn: 0,
      pool: 0,
      sleeping: 0,
      lobster: 0,
      squishy: 0,
      sweater: 0,
      time: 0,
      retro: 0,
      beach: 0,
      reindeer: 0
    },
    D: {
      friar: 0,
      newyork: 0,
      corn: 0,
      pool: 0,
      sleeping: 0,
      lobster: 0,
      squishy: 0,
      sweater: 0,
      time: 0,
      retro: 0,
      beach: 0,
      reindeer: 0
    }
  },
  2: {
    A: {
      friar: 0,
      newyork: 0,
      corn: 0,
      pool: 0,
      sleeping: 0,
      lobster: 0,
      squishy: 0,
      sweater: 0,
      time: 0,
      retro: 0,
      beach: 0,
      reindeer: 0
    },
    B: {
      friar: 0,
      newyork: 0,
      corn: 0,
      pool: 0,
      sleeping: 0,
      lobster: 0,
      squishy: 0,
      sweater: 0,
      time: 0,
      retro: 0,
      beach: 0,
      reindeer: 0
    },
    C: {
      friar: 0,
      newyork: 0,
      corn: 0,
      pool: 0,
      sleeping: 0,
      lobster: 0,
      squishy: 0,
      sweater: 0,
      time: 0,
      retro: 0,
      beach: 0,
      reindeer: 0
    },
    D: {
      friar: 0,
      newyork: 0,
      corn: 0,
      pool: 0,
      sleeping: 0,
      lobster: 0,
      squishy: 0,
      sweater: 0,
      time: 0,
      retro: 0,
      beach: 0,
      reindeer: 0
    },
    E: {
      friar: 0,
      newyork: 0,
      corn: 0,
      pool: 0,
      sleeping: 0,
      lobster: 0,
      squishy: 0,
      sweater: 0,
      time: 0,
      retro: 0,
      beach: 0,
      reindeer: 0
    }
  }
}
